apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c3bn9xpzf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c3bn9xpzf-python 
  name: c3bn9xpzf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c3bn9xpzf-python 
